name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 */1 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  push:
    branches:
      - "master"
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 5
          feed_list: "https://stackoverflow.com/feeds/user/4214976,https://techcrunch.com/feed/,https://blogs.nasa.gov/webb/feed,https://www.space.com/feeds/all"
